tc_sample_app/config/routes.rb
Lumos::Application.routes.draw do

  mount Lti2Tc::Engine, at: '/lti2_tc'

  resources :registries
  resources :results

  match "docs", :to => "docs#show"
  
  get "home/index"

  root :to => "home#index"

  ActiveAdmin.routes(self)

  post '/admin/register_new_tool', :to => 'admin/register_new_tool#index'

  devise_for :admin_users, ActiveAdmin::Devise.config

end

tc_sample_app/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  has_many :enrollments
  has_many :grade_results
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :user_id, :first_name, :last_name, :email, :role, 
        :password, :password_confirmation, :remember_me
  alias_attribute :name, :user_id 
  
  # For variable subsitition
  def user_resolver(fieldname)
    case fieldname
    when "id"
      self.id
    when "username"
      self.email
    end
  end
  
  def person_resolver(fieldname)
    case fieldname
    when "name.family"
      self.last_name
    when "name.full"
      "#{self.first_name} #{self.last_name}"
    when "name.given"
      self.first_name
    when "email.primary"
      self.email
    when "sourcedId"
      self.user_id
    end
  end
end

tc_sample_app/app/models/course.rb
class Course < ActiveRecord::Base
  has_many :enrollments
  has_many :links
  has_many :grade_items
  has_many :grade_results
  has_many :tool_settings, :as => :scopeable
  
  attr_accessible :course_label, :course_title
  alias_attribute :name, :course_label 
  
  def course_resolver(fieldname)
    case fieldname
    when "label"
      self.course_label
    when "title"
      self.course_title
    end
  end
  
end

tc_sample_app/app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
    belongs_to :admin_user
    belongs_to :course
    
    attr_accessible :admin_user_id, :role, :course_id
    
    def to_s
      self.course.course_label
    end
end

tc_sample_app/app/models/grade_item.rb
class GradeItem < ActiveRecord::Base
  belongs_to :course
  
end

tc_sample_app/app/models/grade_result.rb
class GradeResult < ActiveRecord::Base
  belongs_to :course
  belongs_to :admin_user
  
  attr_accessible :id, :link_id, :admin_user_id
  
  def grade_result_resolver(fieldname)
    case fieldname
    when "sourcedGUID"
      self.id.to_s
    when "sourcedId"
      self.id.to_s
    when "uri"
      tool_consumer_registry = Rails.application.config.tool_consumer_registry
      base_url = tool_consumer_registry.tc_deployment_url
      "#{base_url}/results/#{self.id}"
    end
  end
  
end

tc_sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tc_sample_app/app/controllers/docs_controller.rb
class DocsController < ApplicationController
  
  def show
    filename = params['filename'] 
    if filename =~ /.pdf$/
      send_file filename, :disposition => 'inline'
    else
      render :file => filename
    end
  end

end

tc_sample_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

tc_sample_app/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def pre_process
    Lti2Tc::Authorizer::pre_process_tenant(request)
  end

  def show
    oauth_error = pre_process
    (render :text => "Authentication error", :status => 401 if oauth_error) and return
    begin
      grade_result = GradeResult.find(params['id'])
      result_json_object = {
        '@context' => "http://purl.imsglobal.org/ctx/lti/v2/Result",
        '@type' => "Result",
        'resourceScore' => { '@type' => 'decimal', '@value' => "#{grade_result.result}" }
      }
      
      render :json => result_json_object
    rescue
      raise ActionController::RoutingError.new('Not Found')
    end
  end
  
  def update
    oauth_error = pre_process
    (render :text => "Authentication error", :status => 401 if oauth_error) and return
    begin
      grade_result = GradeResult.find(params['id'])
      body_str = request.body.read
      json_str = CGI::unescape body_str
      result_wrapper = JsonWrapper.new(json_str)   
      score_str = result_wrapper.first_at('resultScore')['@value'] 
      grade_result.result = Float(score_str)
      grade_result.save
    rescue
      raise ActionController::RoutingError.new('Not Found')
    end
    
    render :nothing => true
  end
end

tc_sample_app/app/helpers/application_helper.rb
module ApplicationHelper
end

tc_sample_app/app/helpers/home_helper.rb
module HomeHelper
end

tc_sample_app/app/views/admin/course_page/_course_page.html.haml
:javascript
  jQuery(document).ready(function () {
    $('#new_link_section').hide()
  });
  
  function verify_delete_link(course_id, link_id, resource_link_label) {
    if (confirm('Are you sure you want to delete ' + (resource_link_label + '?'))) {
      window.location.href = "/admin/course_page?method=delete&course_id=" + (course_id + "")
          + "&link_id=" + link_id
    }
    return false
  }
  
  function toggle_new_link() {
    $('#new_link_section').toggle()
  }
  
- @course = request['course']
- @links = request['links']
- @resource_list = request['resource_list']
- @resource_map = request['resource_map']
- @grade_item_list = request['grade_item_list']
- @grade_item_map = request['grade_item_map']

:textile

  h3. LuMoS -- Link Actions
  
  h4. Welcome #{current_admin_user.first_name} #{current_admin_user.last_name} [ #{current_admin_user.role} ]
  
  h4. Course #{@course.course_label}
  
%h5
  %a{:href => "course_actions"} [Return to Courses]

%table
  %tr
    %td
      %h4 Link Label
    %td
    %td
    %td
      %h4 Resource
    %td
      %h4 Grade Item
    %td
      %h4 Grade
    %td
      %h4 Custom parameters
  - @links.each do |link|
    -# students don't see disabled links
    - if link['is_link_visible'] 
      %tr
        %td{:width => "150"}
          - if link.is_enabled
            %a{:href=>"#{link['url']}"} #{link.resource_link_label}
          -else
            #{link.resource_link_label}&nbsp;[disabled]
        %td{:width => "50"}
          - if request['is_non_student']
            %a{:href=>"#", :onclick => "return verify_delete_link(\"#{@course.id}\",\"#{link.id}\",\"#{link.resource_link_label}\")"} [delete-link]
          - else
            &nbsp;
        %td{:width => "70"}
          %a{:href=>"/admin/course_page?method=toggle&course_id=#{@course.id}&link_id=#{link.id}&toggle=#{not link.is_enabled}"} [#{link['toggle_label']}]          
        %td{:width => "100"}
          #{link.resource.name}
        %td{:width => "100"}
          #{link.grade_item_label}
        %td{:width => "60"}
          #{link['grade_result']}
        %td
          #{link.link_parameters}
    
%h5
  %a{:href => "#", :onclick => "return toggle_new_link()"} [New Link]
  
%dev#new_link_section
  %h4 New Link Section
  
  %form{:method => "post", :action => "/admin/course_page?method=newtool&course_id=#{@course.id}&"}
    %fieldset
      %ol
        %li
          %label{:for => "msg[resource_link_label]"} Link label
          %input(type="text" name="resource_link_label" value="" maxlength="50")

        %li
          %label{:for => "msg[select_tool]"} Select tool
          %select{:name => "resource_id"}
            - @resource_list.each do |resource_id|
              %option{:value => "#{resource_id}"}
                #{@resource_map[resource_id]}
        %li
          %label{:for => "select_tool"} Custom parameters 
          %textarea{:name => "custom_parameters", :cols => "50"}

        %li
          %label{:for => "msg[grade_item]"} Select gradebook lineitem
          %select{:name => "grade_item_id"}
            - @grade_item_list.each do |grade_item_id|
              %option{:value => "#{grade_item_id}"}
                #{@grade_item_map[grade_item_id]}
                
        %li
          %label
          %input{:name => "is_name_permission", :type => "checkbox", :checked => true}
            Allow sending of name information

        %li
          %label
          %input{:name => "is_email_permission", :type => "checkbox", :checked => true}
            Allow sending the email address

        %li
          %label
          %input{:name => "is_enabled", :type => "checkbox", :checked => true}
            Create Link as Enabled

        %li
          %label
          %input{:type => "submit", :value => "Create Link"}
          

tc_sample_app/app/views/admin/dashboard/_dashboard.html.haml
:textile

  h3. LuMoS -- Lightweight Learning Management System
    
  h4. Welcome #{current_admin_user.first_name} #{current_admin_user.last_name} [ #{current_admin_user.role} ]
  
    
- if current_admin_user.role.downcase == "administrator"
  
  :textile  
    h3. * "Admin Functions":/admin/admin_actions
 
:textile
    
  h3. * "My Courses":/admin/course_actions
  
  h3. * "LTI2 Docs":/admin/documentation

tc_sample_app/app/views/admin/documentation/_documentation.html.haml
:javascript
  function render_document(filename) {
    window.open('/docs?filename=' + filename, "_blank")
  }
  
  function render_site(site) {
    window.open(site, "_blank")
  }

:textile

  h3. LuMoS -- Documentation


%h4
  %a{:href => "#", :onclick => "return render_site(\"http://www.imsglobal.org/lti/index.html\");"} LTI2 Documentation Site

  
%h4
  %a{:href => "#", :onclick => "return render_site(\"https://github.com/IMSGlobal/lti2_tc/blob/master/README.md\");"} LTI2 Tool Provider Readme

  
%h4
  %a{:href => "#", :onclick => "return render_site(\"https://github.com/IMSGlobal/lti2_tc/blob/master/README.md\");"} LTI2 Tool Consumer Readme

  
%h4
  %a{:href => "#", :onclick => "return render_site(\"https://github.com/IMSGlobal/lti2_commons/blob/master/README.md\");"} LTI2 Commons Readme

  

tc_sample_app/app/views/admin/tool_actions/_tool_actions.html.haml
:javascript
  function show_tool_consumer_profile(tool) {
    window.open('tcp_url')
  }
  
:textile

  h3. LuMoS -- Tool Actions

- @tools = request['tools']

%table
  %tr
    %td
      %h4 Tool
    %td
      %h4 Description
    %td
      %h4 Key
    %td
      %h4 Enabled?
    %td
      %h4 New ToolProxy?

  - @tools.each do |tool|
    %tr
      %td{:width => "50"}
        #{tool.product_name}
      %td{:width => "100"}
        #{tool.description}
      %td{:width => "50"}
        #{tool.key}
      %td{:width => "30"}
        %a{:href=> "/admin/tool_actions?method=toggle&tool_id=#{tool.id}&toggle=#{not tool.is_enabled}"} #{tool['toggle_label']}
      %td{:width => "30"}
        #{tool['new_tool_proxy_url'].html_safe}
      %td{:width => "30"}
        %a{:href=> "/admin/tool_actions?method=reregister&tool_id=#{tool.id}"} [re-register]

tc_sample_app/app/views/home/index.html.haml
:textile

  h1. LuMoS
  
  h2. LTI 2.x Tool Consumer